---
 spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/workshop_stock
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    show_sql: true

 server:
     port: ${vcap.application.port:8090}

 eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    hostname: localhost

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80